PhysBoneからSpringBoneへのパラメーター変換を修正
esperecyan/UniVRMExtensions pull request #11
Opened 2023-07-15 00:29 UTC by takecccc

* Pullが0～1に対して、StiffnessForceは0～4。強度の変換はガンマ変換に変更。
* Springが0～1に対して、DragForceは0～1。強度の変換はガンマ変換に変更。(DragForceが1を超えると暴れていました。)
* Gravityの値をパラメータ変換アルゴリズムで制御できていなかったのでパラメータに追加。
* コライダーの高さ方向が誤っていたので修正。

2023-09-07 04:45 UTC, esperecyan commented
Pull Requestありがとうございます。
とりあえずカプセルコライダーの高さの方向が間違っていた件について取り込ませていただきました。

2023-09-07 05:15 UTC, esperecyan requested changes
DynamicBoneParametersにもGravityの追加をお願いします。

2023-09-07 05:15 UTC, esperecyan commented on SwayingObjects/VRCPhysBoneParameters.cs
> +        public float Gravity = 0;
UIに合わせて、GravityはStiffnessとImmobileTypeのあいだに入れてください。

2023-09-07 05:15 UTC, esperecyan commented on SwayingObjects/VRMSpringBoneParameters.cs
> +        public float Gravity = 0.0f;
VRMSpringBoneに合わせて、GravityではなくGravityPowerとしてください。

2023-09-07 05:15 UTC, esperecyan commented on SwayingObjects/VRMSpringBoneParameters.cs
> +        public float Gravity = 0.0f;
GravityDirも追加してください。

2023-09-07 05:15 UTC, esperecyan commented on SwayingObjects/VRMSpringBoneParameters.cs
> +        public float Gravity = 0.0f;
UIに合わせて、GravityPower/GravityDirはStiffnessForceとDragForceのあいだに入れてください。

2023-09-07 05:15 UTC, esperecyan commented on SwayingObjects/VRCPhysBonesToVRMSpringBonesConverter.cs
> +                vrmSpringBone.m_gravityPower = vrcPhysBone.parameters.Gravity;
GravityPower/GravityDirの追加とGravityPower/GravityDirの閾値修正のコミットは分けてください。

2023-09-07 05:44 UTC, esperecyan requested changes

2023-09-07 05:44 UTC, esperecyan commented on SwayingObjects/VRCPhysBoneParameters.cs
> +        public float Gravity = 0;
GravityCurve、GravityFalloff、GravityFalloffCurveも追加してください。

2023-12-19 14:34 UTC, PancakeTorto1se commented
こちらのPRですが少しの間止まっているようですが、取り込みに向けてお手伝いすることは可能でしょうか？
元のコミットに対して上記のコメントを反映させた変更案を作成してみました。
https://github.com/PancakeTorto1se/UniVRMExtensions/tree/fix-converter-parameter

2023-12-19 22:02 UTC, takecccc commented
コメントいただいたまま放置してしまいすみません。
@PancakeTorto1se さんに提案いただいた内容を反映しながら、コミットを整理しました。
パラメーター追加と閾値変更でコミットを分けて欲しいとのコメントがあったので、rebaseして整理してあります。

閾値の調整については当初ガンマ補正を組み合わせていましたが、
変換の根拠がなかったためリニアな範囲変換に変更しました。

各コンポーネントの値の範囲を以下にまとめました。

VRCPhysBone
| param | min | max | default |
| ---   | --- | --- | ---     |
| pull  | 0   |1    | 0.2     |
| spring| 0   |1    | 0.2     |
| stiffness| 0   |1    | 0.2     |
| gravity| -1   |1    | 0     |
| immobile| 0   |1    | 0     |

VRMSpringBone
| param | min | max | default |
| ---   | --- | --- | ---     |
| stiffness| 0 | 4 | 1 |
| gravityPower| 0 | 2 | 0 |
| drag force| 0 | 1 | 0.4 |

DynamicBone
| param | min | max | default |
| ---   | --- | --- | ---     |
| damping | 0 | 1 | 0.1 |
| elasticity | 0 | 1 | 0.1 |
| stiffness | 0 | 1 | 0.1 |
| inert | 0 | 1 | 0.1 |
| gravity | - | - | Vector3(0,0,0) |

2024-01-14 04:20 UTC, esperecyan approved these changes

2024-01-14 04:22 UTC, esperecyan commented
お二方とも有り難うございます。

コードを見ると問題なさそうなのですが、コミットを適用するとなぜかVRMSpringBoneからVRCPhysBoneへの変換で、重力が0になるため、調査中です。

2024-01-14 09:32 UTC, esperecyan commented
↑の件修正できました

2024-01-14 09:35 UTC, takecccc commented
値の代入が漏れていたのですね。ご対応ありがとうございます。

2024-01-14 09:37 UTC, merged

2024-08-17 05:30 UTC, gsdoko0150 commented
こちらについて修正が行われていたようなので確認したのですが、Gravityについては現時点でも閾値を突破して変換されています。（添付画像1枚目がPhysBonesの設定値、2枚目が変換後のSpringboneの設定値です）
数値を見る限り、PhysBones→Springboneで本来はGravityの数値を2倍にするところ、20倍になっているようです（この逆も然りで、本来はSpringbone→PhysBonesでGrabvityの数値を1/2にする必要があるところ、1/20になっているようです）
![image](https://github.com/user-attachments/assets/00b0004c-2400-4de9-907f-99e42503705f)
![image](https://github.com/user-attachments/assets/0cfb416f-4718-4749-b83c-8d599fdf6908)